### ISSUE TITLE
How is that gonna work with static when I18nProvider prevents static generation?

### ISSUE THREAD

**Issue by daniberv** [xairoo/next-i18next-static-site#3]
_app.js wrapped up in I18nProvider can't be statically generated. What's the point? Or am I doing anything wrong that my <body> is empty?

* just've checked your examples and it works the exact same way: no static generation at all https://github.com/xairoo/next-i18next-static-site/tree/main/examples/web-ts

![image](https://user-images.githubusercontent.com/34583263/215112635-1dd757ed-cc02-44e5-83e6-f0d854f813b9.png)

**Comment by xairoo** [comment]
It works without any problems, I am also able to publish the [examples/web](https://github.com/xairoo/next-i18next-static-site/tree/main/examples/web) to Cloudflare Pages using the next static page preset (don't forgot to set to correct Node version until Cloudflare fixed this problem. Build env option `NODE_VERSION` = `v16.7.0`).
https://next-i18next-static-site.pages.dev/de

I have also added an a single example repo for you without `next-transpile`:
https://github.com/xairoo/next-i18next-static-site-cloudflare-pages-example

**Comment by daniberv** [comment]
the screenshot above is made by running your example from this link https://github.com/xairoo/next-i18next-static-site/tree/main/examples/web-ts. And it doesn't work. I mean I run it locally. I have tried to run a local server, then have tried t build and then next start it. Finally have tried to export it. And above you can see what I've got on the screenshot. I don't understand what Cloudflare has to this issue

Nevertheless your approach from this repo https://github.com/xairoo/nextjs-i18n-static-page-starter works like a charm. So thank you. I don't mean to argue with you. Just telling that your code use hydration in the provider to the whole page and it just can't be statically generated

**Comment by xairoo** [comment]
Sorry, I really have no idea what should not work.

I can run both examples, locally and online. Tested on Mac and Windows and on Cloudflare Pages.
Firefox and Chrome.
Also I use this for different projects without any problems.

```
next build && next export
serve out
```

And the web-ts example works (created a extra repo again):
- https://next-i18next-static-site-cloudflare-pages-example-ts.pages.dev/de
- https://github.com/xairoo/next-i18next-static-site-cloudflare-pages-example-ts

![Cloudflare2](https://user-images.githubusercontent.com/731894/215194262-4b8c5cfc-a1e9-4b82-a91b-d4a6f5e5dbb6.png)
![Cloudflare1](https://user-images.githubusercontent.com/731894/215194249-046d4a75-bdfa-45ef-b6c2-3f6c251b2dc3.png)
