### ISSUE TITLE
Install and package requirement

### ISSUE THREAD

**Issue by rdewolff** [xairoo/next-i18next-static-site#4]
While trying our your lib, I am wondering if I need to install the following packages:

- i18next
- react-i18next

Do I need to add these to my project?

Thanks for the clarification 🙌

**Comment by xairoo** [comment]
No, you don't have to.
[next-i18next-static-site](https://github.com/xairoo/next-i18next-static-site) adds all required dependencies like every other NPM package.

Have a look at the example, especially at the [package.json](https://github.com/xairoo/next-i18next-static-site/blob/main/examples/web/package.json).

This [example](https://github.com/xairoo/next-i18next-static-site/tree/main/examples/web) (that's the one with the linked `package.json` above) runs 1:1 on Cloudflare Pages: [https://next-i18next-static-site.pages.dev/de](https://next-i18next-static-site.pages.dev/de).

**Comment by rdewolff** [comment]
It's strange, after adding this package, I had an error in next.js and had to add them manually for the app to run 🤔

**Comment by xairoo** [comment]
My `package.json` looks like this after running `npx create-next-app@latest` and `npm install --save next-i18next-static-site`:

```json
{
  "name": "test-i18n",
  "version": "0.1.0",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "start": "next start",
    "lint": "next lint"
  },
  "dependencies": {
    "next": "13.4.8",
    "next-i18next-static-site": "^0.3.1",
    "react": "18.2.0",
    "react-dom": "18.2.0"
  }
}
```

Both packages `i18next` & `react-i18next` are listed as `peerDependencies` in the [next-i18next-static-site](https://github.com/xairoo/next-i18next-static-site)  [package.json](https://github.com/xairoo/next-i18next-static-site/blob/main/packages/next-i18next-static-site/package.json) and for me it works fine, even with the steps above and a simple setup like the provided [examples](https://github.com/xairoo/next-i18next-static-site/tree/main/examples). Perhaps there was a problem during the installation with NPM?
