### ISSUE TITLE
nextjs config env is not working

### ISSUE THREAD

**Issue by LeeTeng2001** [xairoo/next-i18next-static-site#8]
Putting environmental variables in nextjs config is not working, it only works using .env.local file
next.config.js example:

```
env: {
  NEXT_PUBLIC_I18N_LANGUAGES: '["en", "de"]',
  NEXT_PUBLIC_I18N_DEFAULT_LANGUAGE: "en",
  NEXT_PUBLIC_I18N_NAMESPACES: '["common", "meta", "error"]',
  NEXT_PUBLIC_I18N_DEFAULT_NAMESPACE: "common",
},
```
This will throw 

```
> next dev

  ▲ Next.js 13.5.6
  - Local:        http://localhost:3000

 ✓ Ready in 4.1s
 ✓ Compiled /[lang] in 807ms (397 modules)
Error: NEXT_PUBLIC_I18N_LANGUAGES not set
    at Object.<anonymous> (/Users/lunafreya/Programming/WebstormProjects/personal-portfolio/node_modules/next-i18next-static-site/dist/index.js:82:11)
    at Module._compile (node:internal/modules/cjs/loader:1376:14)
    at Module._extensions..js (node:internal/modules/cjs/loader:1435:10)
    at Module.load (node:internal/modules/cjs/loader:1207:32)
    at Module._load (node:internal/modules/cjs/loader:1023:12)
    at Module.require (node:internal/modules/cjs/loader:1235:19)
```

only works in .env.local file

**Comment by xairoo** [comment]
@LeeTeng2001 is this the full content of your `next.config.js`? If yes, you have done it wrong.
This is how it will typically look like, but can have a lot of more entries (like adding plugins, e.g. MDX stuff):

```
module.exports = {
  env: {
    NEXT_PUBLIC_I18N_LANGUAGES: '["en", "de"]',
    NEXT_PUBLIC_I18N_DEFAULT_LANGUAGE: "en",
    NEXT_PUBLIC_I18N_NAMESPACES: '["common", "meta", "error"]',
    NEXT_PUBLIC_I18N_DEFAULT_NAMESPACE: "common",
  },
});
```

You have to _extend_ your `next.config.js`. Let me know if it’s working! It must, otherwise it is only Next.js related because they read the config and make them available as env. variable(s).

I‘ll update the instructions to prevent this.

**Comment by LeeTeng2001** [comment]
ohh nono, I'm writing it exactly like you laid out. But I agree, the documentation should include the whole config not just the snippet

**Comment by LeeTeng2001** [comment]
Yeah I feel like it's an issue on Next.js side, I'll ask around, thanks. An update on the documentation would be great.

**Comment by xairoo** [comment]
> Yeah I feel like it's an issue on Next.js side, I'll ask around, thanks. An update on the documentation would be great.

Already done ;) 689a98c743a46946fadf7762994cb04c0d1e4b31
