### ISSUE TITLE
App is stuck in infinite loop

### ISSUE THREAD

**Issue by LeoGeneret** [xairoo/next-i18next-static-site#9]
Hello and thanks for this package

I don't know why but looking at the network tab of the devtools, my app is stuck in infinite loop, requesting default locale json too many times at homepage.

Do you have any ideas what I did wrong ?

**Comment by xairoo** [comment]
Have you checked the examples? https://github.com/xairoo/next-i18next-static-site/tree/main/examples
One of the example is live at https://next-i18next-static-site.pages.dev/en, it doesn't have the problem you described.
Try to build it up step by step. Never had this before and I have no idea what you have done.

**Comment by LeoGeneret** [comment]
my bad, finally found the problem. it was a double `languageDetector()` 
thanks for your time

**Comment by LeoGeneret** [comment]
my bad, finally found the problem. it was a double `languageDetector()` 
thanks for your time
